- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      exclude: '^(vendor|http-server)/'
    - id: go-vet
      exclude: '^(vendor|http-server)/'
    - id: go-lint
      exclude: '^(vendor|http-server)/'
    - id: go-imports
      exclude: '^(vendor|http-server)/'
    #- id: go-cyclo
    #  args: [-over=15]
    - id: validate-toml
    # - id: no-go-testing
    # - id: gometalinter
    # - id: golangci-lint
    # - id: go-critic
    # - id: go-unit-tests
    # - id: go-build